# -*- coding: utf-8 -*-
"""my_lora_impl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbSSAtPrN-SY_tzmTaaSlYFBcHQP8h4L
"""

"""

Usage:
    # Train and evaluate
    python lora_pipeline.py

    # Skip training, load existing adapter
    python lora_pipeline.py --skip-training

    # Skip evaluation, classify one article with the tuned model
    python lora_pipeline.py --skip-training --news-only --model tuned --news "Your article here."

    # Classify with both models
    python lora_pipeline.py --skip-training --news-only --model both --news "Your article here."

Dependencies:
    pip install torch transformers peft datasets scikit-learn bitsandbytes accelerate
"""

import argparse
import math
import os
from collections import Counter

import torch
from datasets import load_dataset
from peft import LoraConfig, PeftModel, get_peft_model, TaskType
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    f1_score,
)
from torch.utils.data import DataLoader
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    Trainer,
    TrainingArguments,
    default_data_collator,
)


MODEL_NAME   = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
ADAPTER_PATH = "tinyllama-lora-tuned-news"
LABEL_NAMES  = {0: "World", 1: "Sports", 2: "Business", 3: "Sci/Tech"}


def print_class_distribution(split, label):
    ds = load_dataset("fancyzhx/ag_news", split=split)
    counts = Counter(ds["label"])
    print(f"\nClass distribution: {label} ({split}, {len(ds)} samples)")
    for idx in sorted(counts):
        print(f"  {LABEL_NAMES[idx]:<12} : {counts[idx]}")


def make_prompt(text):
    return (
        "Determine the topic of the news article and respond with one word only: "
        f"World, Sports, Business, or Sci/Tech.\n\nArticle: {text}\n\nTopic:"
    )


def parse_label(raw_output):
    response = raw_output.split("Topic:")[-1].strip().lower()
    first_match, first_pos = None, len(response) + 1
    for idx, name in LABEL_NAMES.items():
        pos = response.find(name.lower())
        if pos != -1 and pos < first_pos:
            first_pos = pos
            first_match = idx
    return first_match if first_match is not None else -1


@torch.no_grad()
def generate_raw(model, tokenizer, text):
    prompt = make_prompt(text)
    input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to("cuda")
    out = model.generate(input_ids, max_new_tokens=10)
    return tokenizer.decode(out[0], skip_special_tokens=True)


# Training

def train(tokenizer):
    print("\nPart 1: Training")

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )

    print("\nLoading base model for training...")
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
    )

    model.enable_input_require_grads()

    lora_config = LoraConfig(
        r=8,
        lora_alpha=16,
        target_modules=["q_proj", "v_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
    )

    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    print("\nLoading and tokenizing dataset (train[:1000])...")
    data = load_dataset("fancyzhx/ag_news", split="train[:1000]")

    def tokenize(batch):
        texts = [
            make_prompt(text) + f" {LABEL_NAMES[label]}"
            for text, label in zip(batch["text"], batch["label"])
        ]
        tokens = tokenizer(
            texts,
            padding="max_length",
            max_length=512,
            truncation=True,
        )
        tokens["labels"] = tokens["input_ids"].copy()
        return tokens

    tokenized_data = data.map(tokenize, batched=True, remove_columns=data.column_names)

    training_args = TrainingArguments(
        output_dir="./tinyllama-news-topic",
        per_device_train_batch_size=4,
        gradient_accumulation_steps=4,
        learning_rate=1e-3,
        num_train_epochs=5,
        fp16=True,
        logging_steps=20,
        save_strategy="epoch",
        report_to="none",
        remove_unused_columns=False,
        label_names=["labels"],
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_data,
        processing_class=tokenizer,
    )

    print("\nTraining..")
    trainer.train()
    print(f"\nSaving adapter to '{ADAPTER_PATH}'...")
    model.save_pretrained(ADAPTER_PATH)
    tokenizer.save_pretrained(ADAPTER_PATH)
    print("Saved")


def load_models(tokenizer):

    print("\nLoading models..")

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )

    base_model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
    ).eval()

    _tmp = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
    )
    tuned_model = PeftModel.from_pretrained(_tmp, ADAPTER_PATH)
    tuned_model = tuned_model.merge_and_unload().eval()
    return base_model, tuned_model


# Evaluation

def evaluate(base_model, tuned_model, tokenizer):
    print("\nPart 2: Evaluation (unseen data: train[1000:1100])")

    print_class_distribution("train[:1000]",     "Training data")
    print_class_distribution("train[1000:1100]",  "Unseen eval data")

    def tokenize_eval(batch):
        texts = [
            make_prompt(text) + f" {LABEL_NAMES[label]}"
            for text, label in zip(batch["text"], batch["label"])
        ]
        tokens = tokenizer(
            texts,
            padding="max_length",
            truncation=True,
            max_length=512,
            return_tensors="pt",
        )
        tokens["labels"] = tokens["input_ids"].clone()
        return tokens

    ds = load_dataset("fancyzhx/ag_news", split="train[1000:1100]")
    ds = ds.map(tokenize_eval, batched=True, remove_columns=["text", "label"])
    ds = ds.with_format("torch")
    loader = DataLoader(ds, batch_size=8, collate_fn=default_data_collator)

    @torch.no_grad()
    def compute_perplexity(model):
        losses = []
        for batch in loader:
            batch = {k: v.to("cuda") for k, v in batch.items()}
            losses.append(model(**batch).loss.item())
        return math.exp(sum(losses) / len(losses))

    print("\nPerplexity")
    print(f"  Base model:  {compute_perplexity(base_model):.2f}")
    print(f"  Tuned model: {compute_perplexity(tuned_model):.2f}")

    raw = load_dataset("fancyzhx/ag_news", split="train[1000:1100]")

    print("\nClassification metrics")
    for name, model in [("Base model (zero-shot)", base_model), ("Tuned model (LoRA)", tuned_model)]:
        preds, refs = [], []
        for item in raw:
            preds.append(parse_label(generate_raw(model, tokenizer, item["text"])))
            refs.append(item["label"])

        acc  = accuracy_score(refs, preds)
        bacc = balanced_accuracy_score(refs, preds)
        f1   = f1_score(refs, preds, average="macro", zero_division=0)

        print(f"\n  {name}")
        print(f"    Accuracy:          {acc:.4f}")
        print(f"    Balanced accuracy: {bacc:.4f}")
        print(f"    Macro F1:          {f1:.4f}")
        print(f"\n    Per-class results:")
        print(classification_report(
            refs, preds,
            labels=list(LABEL_NAMES.keys()),
            target_names=list(LABEL_NAMES.values()),
            zero_division=0,
        ))


def main():
    parser = argparse.ArgumentParser(description="LoRA fine-tuning pipeline for AG News classification.")
    parser.add_argument("--skip-training", action="store_true",
                        help="Skip training and load existing adapter from disk.")
    parser.add_argument("--news-only", action="store_true",
                        help="Skip evaluation, only classify the --news article.")
    parser.add_argument("--model", choices=["base", "tuned", "both"], default="both",
                        help="Which model to use for --news classification (default: both).")
    parser.add_argument("--news", type=str, default=None,
                        help="News article text to classify directly from the command line.")
    args = parser.parse_args()

    print(f"Loading tokenizer: {MODEL_NAME}")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)

    if args.skip_training:
        if not os.path.exists(ADAPTER_PATH):
            print(f"Adapter not found at '{ADAPTER_PATH}'. Run without --skip-training first.")
            return
        print(f"Skipping training. Loading adapter from '{ADAPTER_PATH}'.")
    else:
        train(tokenizer)

    base_model, tuned_model = load_models(tokenizer)

    if not args.news_only:
        evaluate(base_model, tuned_model, tokenizer)

    if args.news:
        print(f"\nArticle: {args.news[:100]}...")

        if args.model in ("base", "both"):
            base_raw  = generate_raw(base_model, tokenizer, args.news)
            base_pred = parse_label(base_raw)
            print(f"\nBase model (zero-shot)")
            print(f"  Raw output:\n  {base_raw}")
            print(f"  Parsed label: {LABEL_NAMES.get(base_pred, 'unparseable')}")

        if args.model in ("tuned", "both"):
            tuned_raw  = generate_raw(tuned_model, tokenizer, args.news)
            tuned_pred = parse_label(tuned_raw)
            print(f"\nTuned model (LoRA)")
            print(f"  Raw output:\n  {tuned_raw}")
            print(f"  Parsed label: {LABEL_NAMES.get(tuned_pred, 'unparseable')}")


if __name__ == "__main__":
    main()